### ISSUE TITLE
Some errors in colorpicker?

### ISSUE THREAD

**Issue by lonkaars** [sdushantha/farge#19]
Colorpicker works fine on my pc, but farge doesn't seem to do anything. When I try to run farge, it outputs

```
(colorpicker:150836): Gdk-CRITICAL **: 11:19:12.888: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(colorpicker:150836): Gdk-CRITICAL **: 11:19:12.888: IA__gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(colorpicker:150836): Gdk-CRITICAL **: 11:19:12.888: IA__gdk_pointer_grab: assertion 'window != NULL' failed
```
to the console, and doesn't exit afterwards. I think gdk has something to do with gnome, which isn't installed on my system but I don't see why farge would depend on gnome. I run x11 with compton and i3 on arch if it helps.

**Comment by sdushantha** [comment]
@lonkaars That is really strange because I have a really similar setup as you. I run Manjaro with i3, X11 and compton.

Im sure this has nothing to do with the issue, but are you by any chance accessing your PC through SSH? Because from looking at the error `GDK_IS_DISPLAY (display)' failed` I feel like `$DISPLAY` isnt found. Its just a guess.

**Comment by lonkaars** [comment]
I'm not accessing over SSH but tried this:
```
 ~ $ echo $DISPLAY                     
:0
 ~ $ farge                                                

(colorpicker:18842): Gdk-CRITICAL **: 19:03:17.919: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(colorpicker:18842): Gdk-CRITICAL **: 19:03:17.919: IA__gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(colorpicker:18842): Gdk-CRITICAL **: 19:03:17.919: IA__gdk_pointer_grab: assertion 'window != NULL' failed
^C
 ✘ ~ $ DISPLAY=0:0
 ~ $ farge      

(colorpicker:19141): Gdk-CRITICAL **: 19:03:25.128: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(colorpicker:19141): Gdk-CRITICAL **: 19:03:25.128: IA__gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(colorpicker:19141): Gdk-CRITICAL **: 19:03:25.128: IA__gdk_pointer_grab: assertion 'window != NULL' failed
^C
 ✘ ~ $ 
```

**Comment by sdushantha** [comment]
I honestly do not know what the issue might be. Maybe @ym1234 might know something about this because they are the one who wrote `colorpicker` ?

**Comment by ym1234** [comment]
Are you sure that's the one I wrote? The code for mine uses no gtk whatsoever.

**Comment by ym1234** [comment]
https://github.com/sdushantha/farge/issues/4 This looks like the same problem.

**Comment by sdushantha** [comment]
@ym1234 Oh that makes sense! Because I was searching for the word "Gdk" in your code and wasn't able to find it, which got me very confused. Thank you for helping out! :+1: 

@lonkaars You might have installed the wrong `colorpicker` if you installed `kunst` from the AUR. Using the `colorpicker` that is linked in the README will most likely solve your problem :blush:

**Comment by lonkaars** [comment]
I installed farge from the arch user repository and it automatically installed colorpicker along with it (which I assume would be the right one). I also don't have kunst installed.

Here's the output of colorpicker:
```
 ~ $ colorpicker                                                                        
R:  19, G:  23, B:  27 | Hex: #13171B
R:  21, G:  24, B:  28 | Hex: #15181C
R:  21, G:  23, B:  26 | Hex: #15171A
R:  27, G:  28, B:  30 | Hex: #1B1C1E
 ~ $
```

**Comment by sdushantha** [comment]
> I also don't have kunst installed.

Oh I'm so sorry!! I meant, `farge`. I accidently typed the wrong name because I was working on another project called `kunst`.

> I installed farge from the arch user repository and it automatically installed colorpicker along with it (**which I assume would be the right one**)

Its unfortunately the wrong one. I am not the maintainer of that AUR repo, so I cant make any changes.

Could you try manually installing `farge` from this repo? The instructions can be found in the README. Also, use this colorpicker instead: https://github.com/ym1234/colorpicker

Let me know if this solves the problem you are having.

**Comment by lonkaars** [comment]
Thanks! It works now. I'll mark the AUR package out-of-date and hope the author will update it.

**Comment by ym1234** [comment]
I was thinking of breaking off the fork relationship and renaming colorpicker since it's such a generic name, but seeing how many people are using this (or at least have it starred) I don't think that'll be the best idea.

**Comment by sdushantha** [comment]
@ym1234 If you want, you could maybe create a new repo with the new name, but keep the old one with a notice telling people to go to the new repo instead.
