### ISSUE TITLE
color picker with zoom?

### ISSUE THREAD

**Issue by Barbaross93** [sdushantha/farge#21]
It can be a bit tricky to pinpoint a color that I want. `gpick` gives the user a little zoomed in window next to the pointer to make it obvious what you're selecting. Would it be possible to have such a feature in farge? Possibly even use `gpick` as an alternative backend?

**Comment by sdushantha** [comment]
> It can be a bit tricky to pinpoint a color that I want

I completely agree with you but that is the disadvantage of using `farge` at the moment. We can't add that feature to farge because uses [`colorpicker`](https://github.com/ym1234/colorpicker) to pick the color. It would be better to create an issue on that project requesting the feature for zooming. 

> Possibly even use `gpick` as an alternative backend?

That is a great idea! I currently do not use Linux, but when I get back to my Linux machine, I will work integrating `gpick` into `farge` :)
